// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Bf2KUDoaN1K33dbaB8Gsu10g4jEfIsI',
    appId: '1:550855798481:web:47b14aa947132499c55ff0',
    messagingSenderId: '550855798481',
    projectId: 'pokermy-b50c0',
    authDomain: 'pokermy-b50c0.firebaseapp.com',
    storageBucket: 'pokermy-b50c0.appspot.com',
    measurementId: 'G-WV0HBTE2JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgsCNN8O5gLfwUNq-s5IxAGreZGR6ikuI',
    appId: '1:550855798481:android:1f36968c41d27a5ac55ff0',
    messagingSenderId: '550855798481',
    projectId: 'pokermy-b50c0',
    storageBucket: 'pokermy-b50c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgIi5FFaFuTBGgiS7E9OIMLGfKtW4i35Y',
    appId: '1:550855798481:ios:3edd58e6ee648f77c55ff0',
    messagingSenderId: '550855798481',
    projectId: 'pokermy-b50c0',
    storageBucket: 'pokermy-b50c0.appspot.com',
    iosBundleId: 'com.pokercmg31.pokerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgIi5FFaFuTBGgiS7E9OIMLGfKtW4i35Y',
    appId: '1:550855798481:ios:3edd58e6ee648f77c55ff0',
    messagingSenderId: '550855798481',
    projectId: 'pokermy-b50c0',
    storageBucket: 'pokermy-b50c0.appspot.com',
    iosBundleId: 'com.pokercmg31.pokerapp',
  );
}
